### PR TITLE
bump version 3.2.0-0

### PR DESCRIPTION
**Pull request by chipironcin**

### CODE REVIEW

**Comment by chipironcin** [comment]
test this please

**Comment by migmartri** [comment]
test this please

**Comment by chipironcin** [comment]
test this please

**Comment by chipironcin** [comment]
test this please

**Comment by chipironcin** [comment]
test this please

**Comment by chipironcin** [comment]
Released new working version at:
https://github.com/bitnami/bitnami-docker-mongodb/releases/tag/3.2.5-0

Closing this PR

**Pull request closed without merging**
