### PR TITLE
introduce custom file initialization

### PR DESCRIPTION
**Pull request by mostafahussein**
**Description of the change**

This PR adds the ability to run custom JS and BASH at `/docker-entrypoint-initdb.d` so we can do mongo operations like create users or more than one database.

**Benefits**

The official mongodb docker image already supports this feature and also other users requested the same feature for other bitnami images like MariaDB and MySQL so it would be useful to have.

**Additional information**
I have added my code to one dockerfile only until you review the code before adding it to rest of `run.sh` and `Dockerfiles`

Also If this PR got accepted I will work on adding the support to mongodb chart to support it which will be similar to what maraidb and mysql charts provide

Thanks

### CODE REVIEW

**Comment by prydonius** [comment]
@juan131 can you take a look at this?

**Comment by tompizmor** [comment]
Hello @mostafahussein,

Thanks a lot for working on this! I see that you are following a very similar approach to the one used in MySQL, MariaDB, and PostgreSQL so in general, it looks good to me. I will give a try when I have a chance.

In any case, we can't just merge this PR as the Dockerfiles and scripts comes from our internal system so we need to apply the changes there. I will create a task so we can plan this work and add this feature to the mongodb container. I will update this PR with any news.

Thanks again! 🙂

**Comment by tompizmor** [comment]
Hi @mostafahussein!

This is just a quick note to let you know that we have integrated this feature in the latest MongoDB releases. Please take a look at the readme:

https://github.com/bitnami/bitnami-docker-mongodb#initializing-a-new-instance

I will close this PR. Thanks for the contribution!

**Comment by nennete** [comment]
Hi @tompizmor , apparently,  this functionality does not work. 

I cannot see any trace in the logs which detects if in the given folder there are `sh` or `js` scripts. 
I cannot manage to find any mention to `docker-entrypoint-initdb.d` folder in source code (`run`, `entry`, etc. scripts)

Please, can you point me to the script which executes the `sh` or `js` scripts from `docker-entrypoint-initdb.d` folder? Thanks a lot

@mostafahussein How are you doing this at the end? Thanks

**Comment by mostafahussein** [comment]
@nennete It seems for some reason they support of executing scripts was [dropped](https://github.com/bitnami/bitnami-docker-mongodb/commit/9d3d27bae07760fc320f50dbaeb53be1402f02e5#diff-1c7d3e2b8a07cecbe436625d36aa2a30) in the last release but I am not sure why. If you strongly need this feature I suggest that you build your own image as sending the PR again to be merged might not be the best option in case bitnami have decided to end the support of this feature. Or you might go with the official mongodb image if it covers your needs as it has support for executing scripts

**Comment by tompizmor** [comment]
Hi @nennete, 

Thanks for reporting this issue. It seems that we forget to implement this functionality when we migrate the MongoDB container to be bash based. 

We will add it again once we find the time and let you know when it is ready.

**Comment by mostafahussein** [comment]
@tompizmor , Is there anything that i can do from my side ?

**Comment by tompizmor** [comment]
If you are in a hurry you can check what we already do for other databases (mariadb, mysql or postgresql) as the approach would be basically the same.

For example, for MariaDB we call to the `msyql_custom_init_scripts` in the setup.sh script. The function definition can be found [here](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.3/debian-9/rootfs/libmysql.sh#L770-L798)

**Comment by alemorcuq** [comment]
Hi, @mostafahussein.

We've released a new bunch of containers that reimplement this feature. They are the following:

- `3.6.13-debian-9-r67`
- `3.6.13-ol-7-r69`
- `4.0.11-debian-9-r14`
- `4.0.11-ol-7-r14`
- `4.1.13-debian-9-r74`
- `4.1.13-ol-7-r77`

Please, let us know if it's working as expected for you.

Regards,
Alejandro

**Pull request closed without merging**
